[package]
name = "openai"
version = "0.9.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
thiserror = "1.0.48"
reqwest = { package = "reqwest-impersonate", version ="0.11.48", default-features = false, features = [
    "boring-tls", "impersonate","json", "cookies", "stream", "multipart", "socks"
] }
hyper = { package = "hyper_imp", version = "0.14.29", default-features = false, features = [
    "client",
] }
trust-dns-resolver = { version = "0.23.2", default-features = false, features = ["system-config", "tokio-runtime"] }
tokio = { version = "1.35.1", features = ["fs", "sync", "signal", "rt-multi-thread"] }
serde_json = "1.0.107"
serde = {version = "1.0.188", features = ["derive"] }
regex = "1.9.5"
async-recursion = "1.0.5"
url = { version = "2.5.0", features = ["serde"] }
base64 = "0.21.4"
rand = "0.8.5"
async-trait = "0.1.73"
typed-builder = "0.18.0"
jsonwebtokens = "1.2.0"
sha2 = "0.10.7"
futures-core = { version = "0.3.28", optional = true}
tera = { version = "1.19.1", default-features = false, optional = true }
hotwatch = "0.5.0"
moka = { version = "0.12.1", default-features = false, features = ["sync"], optional = true }
cidr = { version = "0.2.2", features = ["serde"] }

# redis limit
redis = { version = "0.23.3", features = ["tokio-comp", "tokio-rustls-comp"], optional = true }
redis-macros = { version = "0.2.1", optional = true }

# stream
tokio-util = { version = "0.7.8", features = ["codec"], optional = true }
tokio-stream = { version = "0.1.14", optional = true }
futures = { version = "0.3.28", optional = true }
eventsource-stream = { version = "0.2.3", optional = true }
pin-project-lite = { version = "0.2.13", optional = true }
nom = { version = "7.1.3", optional = true }
mime = { version = "0.3.17", optional = true }
futures-timer = { version = "3.0.2", optional = true }

# mitm
mitm = { path = "../mitm", optional = true }

# arkose
aes = "0.8.3"
md5 = "0.7.0"
cbc = "0.1.2"

# axum
axum = { version = "0.6.20", features = ["http2", "multipart", "headers"], optional = true }
axum-extra ={ version = "0.8.0", features = ["cookie"], optional = true }
axum-server = { version = "0.5.1", features = ["tls-rustls"], optional = true }
tower-http = { version = "0.4.4", default-features = false, features = ["cors", "trace", "map-request-body", "util"], optional = true }
tower = { version = "0.4.13", default-features = false, features = ["limit", "timeout"], optional = true}
bytes = { version = "1.5.0", optional = true }
time = { version =  "0.3.30", optional = true }
static-files = { version = "0.2.3", optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"], optional = true }
async-stream = { version = "0.3.5", optional = true }
axum_csrf = { version = "0.8.0", features = ["layer"], optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48.0"
default-features = false
features = ["Win32_System_Com_CallObj", "Win32_Foundation", "Win32_Globalization", "Win32_UI_Shell_Common"]

[build-dependencies]
static-files = "0.2.3"

[features]
default = ["serve", "limit", "template", "preauth"]
api = ["stream"]
serve = ["dep:serde_urlencoded", "dep:axum_csrf", "stream", "dep:async-stream", "dep:tracing", "dep:tracing-subscriber", "dep:tower-http", "dep:tower", "dep:bytes", "dep:time", "dep:axum-server", "dep:axum-extra", "dep:axum", "dep:static-files", "dep:futures-core", "dep:tera"]
preauth = ["dep:mitm"]
stream = ["dep:tokio-util", "dep:futures", "dep:tokio-stream", "dep:eventsource-stream", "dep:futures-core", "dep:pin-project-lite", "dep:nom", "dep:mime", "dep:futures-timer"]
remote-token = []
limit = ["dep:redis", "dep:redis-macros", "dep:moka"]
template = []

[lib]
name = "openai"
path = "src/lib.rs"

[profile.dev]
opt-level = 'z'

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
strip = true
